### PR TITLE
[#33] "Polyfill" URL.createObjectURL

### PR DESCRIPTION
**Pull request by stereobooster**
Technically this is not Polyfill, but simple stub. But it works at least in my case.

The question is, if there a more right way to do "polyfils" in my project instead of pushing it to this repo? How to do it in CRA project?

### CODE REVIEW

**Comment by philpl** [comment]
Hiya, first of all: Sorry, I don't know a whole lot about @geelen's project here, but I've coauthored react-mapbox-gl a while ago.

However, I don't think it's advisable to add polyfill like these one's into react-snapshot. They would just keep coming and growing and add more surface area for bugs and complaints. An API for users to manually add some should be ok, but can't you just add some polyfills for this particular problem to your entrypoint? At least for now? :)

**Comment by geelen** [comment]
No I think this is probably the right place for this, although I'm not sure of this impl. React-snapshot runs JSDOM, which doesn't always have every DOM api, so your app can and does break on compat issues like this.

There might be an issue on JSDOM already about createObjectURL? I'd look but i'm super busy next few days, sorry.

Report back if you find anything?

**Comment by geelen** [comment]
My other thought (which is potentially a fair bit of work) is to reimplement using a real browser like chrome headless. It'd fix things like this, and enable some neat ideas like full-page screenshots for visual regression testing (or just as a visual log).

**Comment by stereobooster** [comment]
> However, I don't think it's advisable to add polyfill like these one's into react-snapshot.

Yes. I said it too. 

> The question is, if there a more right way to do "polyfils" in **my project** instead of pushing it to this repo?

Three options from more desirable to less desirable:

1) fix jsdom, but they will accept PR only if it is real polyfill
2) fix in place e.g. in my project, but for unknown reason this doesn't work
3) fix in react-snapshot

**Comment by stereobooster** [comment]
it is better to do with headless chrome

**Pull request closed without merging**
