### PR TITLE
Support Helmet v5, add `include`/`exclude` support, fix express 200.html rendering, only crawl potential html pages

### LINKED ISSUE #11: Discussing caveat: "Is starting at / and crawling sufficient?"
> "Is starting at / and crawling sufficient? Might there be unreachable sections of your site?"

I think for most well-structured sites this should not be an issue since you can hopefully get to every page that ever existed by just clicking through the web of links...

However, for my use case, I want `react-snapshot` to render a static page that is not linked from anywhere. The page is a variation of one of my form pages, but it only contains the form, not the site layout (header, footer, etc.). (Unfortunately) I use this by embedding this page in another website in an iframe. This is why it doesn't need to be linked anywhere in the main site (it should not be crawled, but it does need to exist statically).

I know the premise of `react-snapshot` is to be zero-configuration so I'm not sure that my use case will be supported, but do you have any ideas how this might look?

### LINKED ISSUE #15: react-snapshot crawl fails
console error below. 
```
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::2999
    at Object.exports._errnoException (util.js:1033:11)
    at exports._exceptionWithHostPort (util.js:1056:20)
    at Server._listen2 (net.js:1270:14)
    at listen (net.js:1306:10)
    at Server.listen (net.js:1397:7)
    at Function.listen (.../node_modules/connect/index.js:217:24)
    at Object.start (.../node_modules/pushstate-server/index.js:44:16)
    at .../node_modules/react-snapshot/lib/Server.js:26:52
    at Server.start (.../node_modules/react-snapshot/lib/Server.js:25:14)
    at exports.default (.../node_modules/react-snapshot/lib/cli.js:31:10)
error Command failed with exit code 1.
```

on now.sh i get this error:
```
at Url.parse (url.js:95:11)
>     at urlParse (url.js:89:5)
>     at Url.resolve (url.js:657:29)
>     at Object.urlResolve [as resolve] (url.js:653:40)
>     at /home/nowuser/src/node_modules/react-snapshot/lib/Crawler.js:96:44
>     at Array.forEach (native)
>     at /home/nowuser/src/node_modules/react-snapshot/lib/Crawler.js:88:83
>     at Array.forEach (native)
>     at Crawler.extractNewLinks (/home/nowuser/src/node_modules/react-snapshot/lib/Crawler.js:86:36)
>     at /home/nowuser/src/node_modules/react-snapshot/lib/Crawler.js:68:15
```

### LINKED ISSUE #17: `react-helmet` v5 no longer works with `react-snapshot`
**Setup**: [Follow this tutorial](https://medium.com/superhighfives/an-almost-static-stack-6df0a2791319) to setup an app with `react-helmet` version 5 or greater.

**Expected**: The snapshot contains a title (or other metadata) specified in a `<Helmet>`

**Actual**: The snapshot contains the head from the `index.html` template without the proper title, etc.

https://github.com/nfl/react-helmet/commit/0ad790830a1121b6c645f4f9a678a60fc604cf94 is the breaking commit in `react-helmet`. It looks like they started batching updates to the dom for better performance. My guess is that the snapshot is taken before the callback is triggered to update the title now.

If this seems like this is the correct place to fix the issue I would be happy to investigate a fix/pr.

### LINKED ISSUE #19: Saving sub routes
Thanks for a very nice library, @geelen . I am learning how I can use it with my brand new create-react-app test site and noticing behavior that I do not understand. I would appreciate your help explaining.

I created the following site structure (urls):
- / - home
- /shop -- list of shopping categories
- /shop/pizza -- list of products in shopping category
- /shop/pizza/margherita -- product page

snapshot output:
?   Starting crawling http://localhost:2999
??   Saving / as /index.html
??   Saving /shop as /shop.html
??   Saving /shop/pizza as /shop/pizza.html
??   Saving /shop/pizza/margherita as /shop/pizza/margherita.html

I run "serve build" and navigate to different urls using Chrome. Here is observed behavior:
- / -- works as expected and home page is loaded
- /shop -- loads folder view of the /shop/ url -- wrong
- /shop/pizza -- loads folder view of the /shop/pizza/url -- wrong
- /shop/pizza/margherita -- returns 404 -- wrong

What is the best approach to handle sub routes? May be I am missing http server config that should handle file layout produced by react-snapshot (other than always serving 200.html for all requests)?

One solution is for every url always produce folder and index.html inside (assuming http server always serves index.html as default doc for folders). My structure will look like:

/index.html
/shop/index.html
/shop/pizza/index.html
/shop/pizza/margherita/index.html

Thanks,
Andrey

### PR DESCRIPTION
**Pull request by haroldhues**
Apologies, it seems I have put a lot into this PR. I was kind of on a roll though. I tried to test as many configurations as I could and it seems pretty stable.

Note: I went ahead and renamed the `path` option to `include` since it wasn`t documented and it appears react-snapshot hasn`t been released yet. But I can make that backward compatible as well...

Fixes #17
Fixes #19
Incorporated #23 and #22 
Fixes #15 and #16 in a few more cases, also handles includes and excludes for basenames
Closes #11

Also various other things I found
 * Only crawl potential html pages (not links to .jpg files for instance)
 * Release resources so that the server can gracefully shutdown
 * Removed hardcoded port
 * Updated readme

### CODE REVIEW

**Comment by geelen** [comment]
Hey! Thanks for this! I'd actually done a little bit of work myself on a few of those, but hadn't finished and merged it. I've just done so now at #26 

There were a few merge conflicts but I've fixed them and pushed the code on the `haroldhues-master` branch (also pointed #27 at it). I'm seeing an error with `ext.pathname` in my local testing, can you take a look and see if maybe something got broken in the merge?

Very keen to get a new release out with these changes in the next few days. Thanks again for picking up a bunch of things at once 👌

**Comment by haroldhues** [comment]
@geelen Path problem is fixed, I could not get `connect-history-api-fallback` to work with my project. I didn't look into it too much, but I replaced it with a simple middleware that I believe will do the same thing. I didn't test if the proxy still works. 🙈 

BTW `create-react-app` also supports [passing an object](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#configuring-the-proxy-manually) to `proxy`. It might be worth handling that case as well :bowtie:

**Comment by geelen** [comment]
Closing in favour of #27

**Comment by geelen** [comment]
Boom. Finally figured out the bugs with this, and have merged & published `v1.0.0`

**Pull request closed without merging**
